### ISSUE TITLE
Green Grocer Lab tests are not running

### ISSUE THREAD

**Issue by ErockEsquire** [learn-co-curriculum/programming-univbasics-nds-green-grocer#7]
The command line only prints:

[15:41:37] (master) programming-univbasics-nds-green-grocer-nyc04-seng-ft-021720// ♥ learn
Grocer
  #find_item_by_name_in_collection takes two arguments: a String and an AoH  and when a contained Hash's :item key matches the String

and then stops

**Comment by ErockEsquire** [comment]
If I ctrl C, this prints:

^CRSpec is shutting down and will print the summary report... Interrupt again to force quit.
Traceback (most recent call last):
        7: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        6: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
        5: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-test:23:in `<main>'
        4: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-test:23:in `load'
        3: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/bin/learn-test:68:in `<top (required)>'
        2: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:16:in `run'
        1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/rspec.rb:36:in `run'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-test-2.6.1/lib/learn_test/strategies/rspec.rb:36:in `system': Interrupt

**Comment by ErockEsquire** [comment]
This is the function it tries to run

def find_item_by_name_in_collection(name, collection)
  index = 0
  while index < collection.length do
    if collection[index][:item] === name
      collection[index]
    else
      index+=1
    end
  end
  nil
end
